# Generated by Django 3.2.5 on 2021-07-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
