# Generated by Django 3.2.5 on 2021-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tab_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reply',
            new_name='reply_post',
        ),
        migrations.AddField(
            model_name='post',
            name='reply_tab',
            field=models.IntegerField(null=True),
        ),
    ]
