# Generated by Django 3.2.5 on 2021-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210723_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_tab',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
