# Generated by Django 3.2.5 on 2021-07-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210723_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_post',
        ),
    ]
